# Generated by Django 5.2.4 on 2025-11-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact_contactmodel_experience_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='svg',
        ),
    ]
