# Generated by Django 5.2.4 on 2025-11-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_skill_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='position',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='positions',
            field=models.ManyToManyField(to='myapp.positionmodel'),
        ),
    ]
