# Generated by Django 5.2.4 on 2025-11-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_profilemodel_position_profilemodel_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='lImage',
        ),
    ]
