# Generated by Django 5.2.4 on 2025-11-07 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_aboutmodel_image_remove_aboutmodel_limage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skillsmodel',
            name='skill',
            field=models.ManyToManyField(to='myapp.lg'),
        ),
    ]
