# Generated by Django 5.2.4 on 2025-11-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_lg_alter_skillsmodel_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='tag',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='title',
        ),
    ]
