# Generated by Django 5.2.4 on 2025-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_tag_feedback_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
