# Generated by Django 5.2.4 on 2025-11-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_education_educationmodel_workexperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='des',
        ),
    ]
