# Generated by Django 5.2.4 on 2025-11-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_servicemodel_des'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationModel',
        ),
        migrations.DeleteModel(
            name='WorkExperienceModel',
        ),
    ]
