# Generated by Django 5.2.4 on 2025-11-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_educationmodel_delete_workexperiencemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
