# Generated by Django 5.2.4 on 2025-11-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
