# Generated by Django 5.2.4 on 2025-11-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_education_title1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioModel',
        ),
    ]
