# Generated by Django 5.2.4 on 2025-11-10 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_portfoliomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSingleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='ProjectSingle')),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('des1', models.CharField(blank=True, max_length=200, null=True)),
                ('des2', models.CharField(blank=True, max_length=200, null=True)),
                ('keyFeature', models.JSONField(blank=True, default=list, null=True)),
                ('image1', models.ImageField(upload_to='ProjectSingle')),
                ('image2', models.ImageField(upload_to='ProjectSingle')),
                ('technologies', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
