# Generated by Django 5.2.4 on 2025-11-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_projectsinglemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsinglemodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projectmodel'),
        ),
    ]
